#!/usr/bin/env bash

# USAGE
# ./makedoc build
# ./makedoc commit
# ./makedoc push

if [ $1 = "build" ]
then
  echo "building ..."
  cd sphinx
  make clean
  make html
  cd ..
fi


if [ $1 = "commit" ]
then
  echo "committing ..."
  # commit and push
  git add -A
  git commit -m "documentation updated"
  git push origin master

  # switch to gh-pages branch and pull docs
  git checkout gh-pages
  rm -rf ./docs
  rm -rf ./tutorial
  rm -rf _*
  touch .nojekyll
  git checkout master docs/html

  # move docs to root and delete docs
  mv ./docs/html/* ./
  rm -rf ./docs
  git checkout master
fi


if [ $1 = "push" ]
then
  echo "pushing ..."
  # push updated gh-pages
  git add -A
  git commit -m "documentation updated"
  git push origin gh-pages
  
  # switch back to master
  git checkout master
fi