#!/usr/bin/env bash

# Run this script within 'sphinx' folder!

# build the docs
make clean
make html

# back to root folder
cd ..

# commit and push
git add -A
git commit -m "documentation updated"
git push origin master

# switch to gh-pages branch and pull docs
git checkout gh-pages
rm -rf ./docs
touch .nojekyll
git checkout master docs/html

# move docs to root and delete docs
mv ./docs/html/* ./
rm -rf ./docs

# push updated gh-pages
git add -A
git commit -m "documentation updated"
git push origin gh-pages

# switch back to master
git checkout master